# Generated by Django 6.0.3 on 2026-07-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
