# Generated by Django 6.0.3 on 2026-07-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0002_clientinfo_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='name_solo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
