# Generated by Django 6.0.3 on 2026-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0003_clientinfo_name_solo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='name_solo',
            field=models.CharField(max_length=200),
        ),
    ]
