# Generated by Django 6.0.1 on 2026-03-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesign',
            name='description',
            field=models.TextField(default='...', max_length=2047),
        ),
    ]
