# Generated by Django 6.0.1 on 2026-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_webdesign_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesign',
            name='design',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
