# Generated by Django 6.0.1 on 2026-03-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_webdesign_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesign',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdesign',
            name='design',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
