# Generated by Django 6.0.1 on 2026-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_webdesign_url_alter_webdesign_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdesign',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
