# Generated by Django 6.0.1 on 2026-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_webdesign_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2047, null=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
