# Generated by Django 6.0.1 on 2026-03-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_webfeatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebFeatures',
            new_name='WebFeature',
        ),
    ]
