# Generated by Django 6.0.1 on 2026-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_webfeatures_webfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdesign',
            name='design',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
