# Generated by Django 6.0.3 on 2026-07-02 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('public', models.BooleanField(default=True)),
                ('sectors', models.ManyToManyField(related_name='designs', to='designs.sector')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
