# Generated by Django 6.0.3 on 2026-08-02 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_design_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Linker',
                'verbose_name_plural': 'Linkers',
            },
        ),
    ]
