# Generated by Django 6.0.3 on 2026-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_linker'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
