# Generated by Django 6.0.3 on 2026-08-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_linker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linker',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
