# Generated by Django 6.0.3 on 2026-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_linker_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='linker',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='linker',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
