# Generated by Django 6.0.3 on 2026-08-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_linker_location_linker_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linker',
            old_name='location',
            new_name='address',
        ),
    ]
